/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ThreatDetection {
    threatType: ThreatType;
    timestamp: Time;
    details: string;
    riskScore: bigint;
    detectionMethod: DetectionMethod;
}
export type Time = bigint;
export enum DetectionMethod {
    BehavioralAnalysis = "BehavioralAnalysis",
    PatternMatch = "PatternMatch",
    ReputationScoring = "ReputationScoring"
}
export enum ThreatType {
    PhishingURL = "PhishingURL",
    Keylogger = "Keylogger"
}
export interface backendInterface {
    analyzeURL(url: string): Promise<ThreatDetection>;
    detectKeylogger(processName: string): Promise<ThreatDetection>;
    getAllDetections(): Promise<Array<ThreatDetection>>;
    getDetectionsByRiskScore(minScore: bigint): Promise<Array<ThreatDetection>>;
    getDetectionsByType(threatType: ThreatType): Promise<Array<ThreatDetection>>;
}
import type { DetectionMethod as _DetectionMethod, ThreatDetection as _ThreatDetection, ThreatType as _ThreatType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeURL(arg0: string): Promise<ThreatDetection> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeURL(arg0);
                return from_candid_ThreatDetection_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeURL(arg0);
            return from_candid_ThreatDetection_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async detectKeylogger(arg0: string): Promise<ThreatDetection> {
        if (this.processError) {
            try {
                const result = await this.actor.detectKeylogger(arg0);
                return from_candid_ThreatDetection_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectKeylogger(arg0);
            return from_candid_ThreatDetection_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDetections(): Promise<Array<ThreatDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDetections();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDetections();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionsByRiskScore(arg0: bigint): Promise<Array<ThreatDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionsByRiskScore(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionsByRiskScore(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionsByType(arg0: ThreatType): Promise<Array<ThreatDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionsByType(to_candid_ThreatType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionsByType(to_candid_ThreatType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DetectionMethod_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetectionMethod): DetectionMethod {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatDetection_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatDetection): ThreatDetection {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatType): ThreatType {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threatType: _ThreatType;
    timestamp: _Time;
    details: string;
    riskScore: bigint;
    detectionMethod: _DetectionMethod;
}): {
    threatType: ThreatType;
    timestamp: Time;
    details: string;
    riskScore: bigint;
    detectionMethod: DetectionMethod;
} {
    return {
        threatType: from_candid_ThreatType_n3(_uploadFile, _downloadFile, value.threatType),
        timestamp: value.timestamp,
        details: value.details,
        riskScore: value.riskScore,
        detectionMethod: from_candid_DetectionMethod_n5(_uploadFile, _downloadFile, value.detectionMethod)
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PhishingURL: null;
} | {
    Keylogger: null;
}): ThreatType {
    return "PhishingURL" in value ? ThreatType.PhishingURL : "Keylogger" in value ? ThreatType.Keylogger : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BehavioralAnalysis: null;
} | {
    PatternMatch: null;
} | {
    ReputationScoring: null;
}): DetectionMethod {
    return "BehavioralAnalysis" in value ? DetectionMethod.BehavioralAnalysis : "PatternMatch" in value ? DetectionMethod.PatternMatch : "ReputationScoring" in value ? DetectionMethod.ReputationScoring : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ThreatDetection>): Array<ThreatDetection> {
    return value.map((x)=>from_candid_ThreatDetection_n1(_uploadFile, _downloadFile, x));
}
function to_candid_ThreatType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatType): _ThreatType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatType): {
    PhishingURL: null;
} | {
    Keylogger: null;
} {
    return value == ThreatType.PhishingURL ? {
        PhishingURL: null
    } : value == ThreatType.Keylogger ? {
        Keylogger: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
