/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DetectionMethod = { 'BehavioralAnalysis' : null } |
  { 'PatternMatch' : null } |
  { 'ReputationScoring' : null };
export interface ThreatDetection {
  'threatType' : ThreatType,
  'timestamp' : Time,
  'details' : string,
  'riskScore' : bigint,
  'detectionMethod' : DetectionMethod,
}
export type ThreatType = { 'PhishingURL' : null } |
  { 'Keylogger' : null };
export type Time = bigint;
export interface _SERVICE {
  'analyzeURL' : ActorMethod<[string], ThreatDetection>,
  'detectKeylogger' : ActorMethod<[string], ThreatDetection>,
  'getAllDetections' : ActorMethod<[], Array<ThreatDetection>>,
  'getDetectionsByRiskScore' : ActorMethod<[bigint], Array<ThreatDetection>>,
  'getDetectionsByType' : ActorMethod<[ThreatType], Array<ThreatDetection>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];