/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ThreatType = IDL.Variant({
  'PhishingURL' : IDL.Null,
  'Keylogger' : IDL.Null,
});
export const Time = IDL.Int;
export const DetectionMethod = IDL.Variant({
  'BehavioralAnalysis' : IDL.Null,
  'PatternMatch' : IDL.Null,
  'ReputationScoring' : IDL.Null,
});
export const ThreatDetection = IDL.Record({
  'threatType' : ThreatType,
  'timestamp' : Time,
  'details' : IDL.Text,
  'riskScore' : IDL.Nat,
  'detectionMethod' : DetectionMethod,
});

export const idlService = IDL.Service({
  'analyzeURL' : IDL.Func([IDL.Text], [ThreatDetection], []),
  'detectKeylogger' : IDL.Func([IDL.Text], [ThreatDetection], []),
  'getAllDetections' : IDL.Func([], [IDL.Vec(ThreatDetection)], ['query']),
  'getDetectionsByRiskScore' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ThreatDetection)],
      ['query'],
    ),
  'getDetectionsByType' : IDL.Func(
      [ThreatType],
      [IDL.Vec(ThreatDetection)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ThreatType = IDL.Variant({
    'PhishingURL' : IDL.Null,
    'Keylogger' : IDL.Null,
  });
  const Time = IDL.Int;
  const DetectionMethod = IDL.Variant({
    'BehavioralAnalysis' : IDL.Null,
    'PatternMatch' : IDL.Null,
    'ReputationScoring' : IDL.Null,
  });
  const ThreatDetection = IDL.Record({
    'threatType' : ThreatType,
    'timestamp' : Time,
    'details' : IDL.Text,
    'riskScore' : IDL.Nat,
    'detectionMethod' : DetectionMethod,
  });
  
  return IDL.Service({
    'analyzeURL' : IDL.Func([IDL.Text], [ThreatDetection], []),
    'detectKeylogger' : IDL.Func([IDL.Text], [ThreatDetection], []),
    'getAllDetections' : IDL.Func([], [IDL.Vec(ThreatDetection)], ['query']),
    'getDetectionsByRiskScore' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ThreatDetection)],
        ['query'],
      ),
    'getDetectionsByType' : IDL.Func(
        [ThreatType],
        [IDL.Vec(ThreatDetection)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };